name: Notify Slack on Push

on:
  push:
    branches:
      - main  # 根據需求修改為監聽的分支

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK:  ${{ secrets.SLACK_WEBHOOK_URL }}  # 使用 GitHub Secrets 中儲存的 Webhook URL
          SLACK_MESSAGE: "Test Message from GitHub Actions" # 先改用簡單純文字測試
          SLACK_USERNAME: "GitHub Actions"
          SLACK_COLOR: "#36a64f"